services:
  - type: web
    name: imposter-artist-server
    env: node
    region: singapore
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: false
